//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_management
{
    using System;
    using System.Collections.Generic;
    
    public partial class Photo
    {
        public long id { get; set; }
        public long room_id { get; set; }
        public byte[] image { get; set; }
    
        public virtual Room Room { get; set; }
    }
}
